version: '3.8'

services:
  app:
    container_name: datafeeder_cli_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: store
      DB_USERNAME: user
      DB_PASSWORD: pass
    command: ["sh", "-c", "while ! mysqladmin ping -h db --silent; do sleep 1; done; composer install; php datafeeder migrate; php datafeeder test; php datafeeder import:products /data/feed.xml"]
    networks:
      - app

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app

networks:

  app:
    driver: bridge

volumes:
  mysql:
